"""Partition tests for every PCUI CloudFormation template.

Every ARN in the templates must use the dynamic partition (${AWS::Partition})
so that PCUI can be deployed in every partition (aws, aws-cn, aws-us-gov, ...).
"""

import pytest
from cloud_radar.cf.unit import Template

from conftest import _apply_foreach
from constants import CFN_TEMPLATES, INFRASTRUCTURE_DIR
from helpers import arns_from_resource

DYNAMIC_PARTITION_ARN_PREFIX = "arn:${AWS::Partition}:"

# ARNs that are expected to have a hardcoded partition, by template and resource.
HARDCODED_PARTITION_ARNS_ALLOWLIST = {
    "parallelcluster-ui.yaml": {
        # Cost Explorer is only available in us-east-1, aws partition.
        # See https://docs.aws.amazon.com/general/latest/gr/billing.html
        "CostMonitoringAndPricingPolicy": {"arn:aws:ce:us-east-1:${AWS::AccountId}:/*"},
    },
}


@pytest.mark.parametrize("template_name", CFN_TEMPLATES)
def test_arns_use_dynamic_partition(template_name: str):
    """ARNs in resource properties must use ${AWS::Partition} rather than
    a hardcoded partition, unless explicitly allowlisted."""
    template = Template.from_yaml((INFRASTRUCTURE_DIR / template_name).resolve(), {})
    # Pre-expand Fn::ForEach so that resources generated by loops are checked too.
    resources = _apply_foreach(template.template).get("Resources", {})
    allowlist = HARDCODED_PARTITION_ARNS_ALLOWLIST.get(template_name, {})

    violations = []
    for resource_name, resource in resources.items():
        allowed_arns = allowlist.get(resource_name, set())
        properties = resource.get("Properties", {})
        for path, arn in arns_from_resource(properties, resource_name):
            if not arn.startswith(DYNAMIC_PARTITION_ARN_PREFIX) and arn not in allowed_arns:
                violations.append(f"{path}: {arn}")

    assert not violations, f"{template_name} contains ARNs with a hardcoded partition: {'\n'.join(violations)}"
