FROM public.ecr.aws/lambda/python:3.9

ARG data_dir=/opt

COPY --from=frontend /app/build ${data_dir}/frontend/public

COPY resources/attributions/docker-attributions.txt license.txt

COPY app.py ${data_dir}
COPY api ${data_dir}/api
COPY awslambda ${data_dir}/awslambda

RUN mkdir -p /data
WORKDIR /opt
RUN python -c "import shutil; shutil.make_archive('/data/layer', format='zip')"

ENTRYPOINT ["bash"]
CMD ["-c", "cp /data/layer.zip /output" ]
