# Bump Version workflow that is triggered manually
name: Bump Version

on:
  workflow_dispatch:
    inputs:
      pcui-version:
        description: 'The target version of ParallelCluster UI (format YYYY.MM.REVISION, e.g. 2026.10.0)'
        required: true
        type: string
      branch:
        description: 'The Github branch name'
        required: true
        type: string

jobs:
  create-pull-request:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: ${{ inputs.branch }}

      - name: Modify code to change version
        env:
          PCUI_VERSION: ${{ inputs.pcui-version }}
        run: ./scripts/bump-version.sh --version "$PCUI_VERSION"

      - name: Create a Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: '[Versioning] Bump PCUI version to ${{ inputs.pcui-version }}.'
          title: '[Versioning] Bump PCUI version to ${{ inputs.pcui-version }}'
          body: |
            This PR contains version bump.
            Auto-generated by Github Action
          branch: versionbump-${{ inputs.branch }}-${{ inputs.pcui-version }}
          delete-branch: true
